services:
  app:
    build:
      context: .
    container_name: app
    volumes:
      - ./data:/data
    environment:
      - DB_FILE=/data/db.sqlite3
      - PW_SERVER=ws://pw:3000/
    env_file:
      - .env
    links:
      - pw
    depends_on:
      - pw
    command: daphne -b 0.0.0.0 -p 3001 byos_django.asgi:application
  pw:
    image: mcr.microsoft.com/playwright:v1.50.0-noble
    container_name: pw
    user: pwuser
    init: true
    volumes:
      - pw_home:/home/pwuser
    command: npx -y playwright@1.50.0 run-server --port 3000 --host 0.0.0.0
  nginx:
    build:
      context: .
    container_name: nginx
    ports:
      - "8000:80"
    links:
      - app
    depends_on:
      - app
    command: nginx -g 'daemon off;'

volumes:
  pw_home:
